// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List        = require("bs-platform/lib/js/list.js");
var Nice        = require("bs-nice/src/nice.js");
var Block       = require("bs-platform/lib/js/block.js");
var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Style");

function make(display, width, height, top, bottom, left, right, minWidth, maxWidth, minHeight, maxHeight, margin, marginVertical, marginHorizontal, marginTop, marginBottom, marginLeft, marginRight, padding, paddingVertical, paddingHorizontal, paddingTop, paddingBottom, paddingLeft, paddingRight, borderWidth, borderTopWidth, borderBottomWidth, borderLeftWidth, borderRightWidth, position, flexDirection, flexWrap, justifyContent, alignItems, alignSelf, alignContent, overflow, flex, flexGrow, flexShrink, flexBasisi, flexBasis, shadowColor, shadowOffset, shadowOpacity, shadowRadius, transform, backfaceVisibilty, backgroundColor, borderColor, borderTopColor, borderBottomColor, borderLeftColor, borderRightColor, borderRadius, borderTopRightRadius, borderBottomLeftRadius, borderBottomRightRadius, borderTopLeftRadius, borderStyle, opacity, elevation, color, fontFamily, fontSize, fontStyle, fontWeight, fontVariant, textShadowOffset, textShadowRadius, textShadowColor, letterSpacing, lineHeight, textAlign, textAlignVertical, includeFontPadding, textDecorationLine, textDecorationColor, writingDirection, resizeMode, tintColor, overlayColor, mediaQuery, supports, select, raw, children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var tmp;
      if (shadowOffset) {
        var match = shadowOffset[0];
        tmp = /* Some */[/* ShadowOffset */Block.__(44, [
              match[0],
              match[1]
            ])];
      } else {
        tmp = /* None */0;
      }
      var tmp$1;
      if (textShadowOffset) {
        var match$1 = textShadowOffset[0];
        tmp$1 = /* Some */[/* TextShadowOffset */Block.__(69, [
              match$1[0],
              match$1[1]
            ])];
      } else {
        tmp$1 = /* None */0;
      }
      var tmp$2;
      if (mediaQuery) {
        var match$2 = mediaQuery[0];
        tmp$2 = /* Some */[/* MediaQuery */Block.__(83, [
              match$2[0],
              match$2[1]
            ])];
      } else {
        tmp$2 = /* None */0;
      }
      var tmp$3;
      if (supports) {
        var match$3 = supports[0];
        tmp$3 = /* Some */[/* Supports */Block.__(84, [
              match$3[0],
              match$3[1]
            ])];
      } else {
        tmp$3 = /* None */0;
      }
      var tmp$4;
      if (select) {
        var match$4 = select[0];
        tmp$4 = /* Some */[/* Select */Block.__(85, [
              match$4[0],
              match$4[1]
            ])];
      } else {
        tmp$4 = /* None */0;
      }
      var tmp$5;
      if (raw) {
        var match$5 = raw[0];
        tmp$5 = /* Some */[/* Raw */Block.__(86, [
              match$5[0],
              match$5[1]
            ])];
      } else {
        tmp$5 = /* None */0;
      }
      var stylesProps_000 = display ? /* Some */[/* Display */Block.__(0, [display[0]])] : /* None */0;
      var stylesProps_001 = /* :: */[
        width ? /* Some */[/* Width */Block.__(1, [width[0]])] : /* None */0,
        /* :: */[
          height ? /* Some */[/* Height */Block.__(2, [height[0]])] : /* None */0,
          /* :: */[
            top ? /* Some */[/* Top */Block.__(3, [top[0]])] : /* None */0,
            /* :: */[
              bottom ? /* Some */[/* Bottom */Block.__(4, [bottom[0]])] : /* None */0,
              /* :: */[
                left ? /* Some */[/* Left */Block.__(5, [left[0]])] : /* None */0,
                /* :: */[
                  right ? /* Some */[/* Right */Block.__(6, [right[0]])] : /* None */0,
                  /* :: */[
                    minWidth ? /* Some */[/* MinWidth */Block.__(7, [minWidth[0]])] : /* None */0,
                    /* :: */[
                      maxWidth ? /* Some */[/* MaxWidth */Block.__(8, [maxWidth[0]])] : /* None */0,
                      /* :: */[
                        minHeight ? /* Some */[/* MinHeight */Block.__(9, [minHeight[0]])] : /* None */0,
                        /* :: */[
                          maxHeight ? /* Some */[/* MaxHeight */Block.__(10, [maxHeight[0]])] : /* None */0,
                          /* :: */[
                            margin ? /* Some */[/* Margin */Block.__(11, [margin[0]])] : /* None */0,
                            /* :: */[
                              marginVertical ? /* Some */[/* MarginVertical */Block.__(12, [marginVertical[0]])] : /* None */0,
                              /* :: */[
                                marginHorizontal ? /* Some */[/* MarginHorizontal */Block.__(13, [marginHorizontal[0]])] : /* None */0,
                                /* :: */[
                                  marginTop ? /* Some */[/* MarginTop */Block.__(14, [marginTop[0]])] : /* None */0,
                                  /* :: */[
                                    marginBottom ? /* Some */[/* MarginBottom */Block.__(15, [marginBottom[0]])] : /* None */0,
                                    /* :: */[
                                      marginLeft ? /* Some */[/* MarginLeft */Block.__(16, [marginLeft[0]])] : /* None */0,
                                      /* :: */[
                                        marginRight ? /* Some */[/* MarginRight */Block.__(17, [marginRight[0]])] : /* None */0,
                                        /* :: */[
                                          padding ? /* Some */[/* Padding */Block.__(18, [padding[0]])] : /* None */0,
                                          /* :: */[
                                            paddingVertical ? /* Some */[/* PaddingVertical */Block.__(19, [paddingVertical[0]])] : /* None */0,
                                            /* :: */[
                                              paddingHorizontal ? /* Some */[/* PaddingHorizontal */Block.__(20, [paddingHorizontal[0]])] : /* None */0,
                                              /* :: */[
                                                paddingTop ? /* Some */[/* PaddingTop */Block.__(21, [paddingTop[0]])] : /* None */0,
                                                /* :: */[
                                                  paddingBottom ? /* Some */[/* PaddingBottom */Block.__(22, [paddingBottom[0]])] : /* None */0,
                                                  /* :: */[
                                                    paddingLeft ? /* Some */[/* PaddingLeft */Block.__(23, [paddingLeft[0]])] : /* None */0,
                                                    /* :: */[
                                                      paddingRight ? /* Some */[/* PaddingRight */Block.__(24, [paddingRight[0]])] : /* None */0,
                                                      /* :: */[
                                                        borderWidth ? /* Some */[/* BorderWidth */Block.__(25, [borderWidth[0]])] : /* None */0,
                                                        /* :: */[
                                                          borderTopWidth ? /* Some */[/* BorderTopWidth */Block.__(26, [borderTopWidth[0]])] : /* None */0,
                                                          /* :: */[
                                                            borderBottomWidth ? /* Some */[/* BorderBottomWidth */Block.__(27, [borderBottomWidth[0]])] : /* None */0,
                                                            /* :: */[
                                                              borderLeftWidth ? /* Some */[/* BorderLeftWidth */Block.__(28, [borderLeftWidth[0]])] : /* None */0,
                                                              /* :: */[
                                                                borderRightWidth ? /* Some */[/* BorderRightWidth */Block.__(29, [borderRightWidth[0]])] : /* None */0,
                                                                /* :: */[
                                                                  position ? /* Some */[/* Position */Block.__(30, [position[0]])] : /* None */0,
                                                                  /* :: */[
                                                                    flexDirection ? /* Some */[/* FlexDirection */Block.__(31, [flexDirection[0]])] : /* None */0,
                                                                    /* :: */[
                                                                      flexWrap ? /* Some */[/* FlexWrap */Block.__(32, [flexWrap[0]])] : /* None */0,
                                                                      /* :: */[
                                                                        justifyContent ? /* Some */[/* JustifyContent */Block.__(33, [justifyContent[0]])] : /* None */0,
                                                                        /* :: */[
                                                                          alignItems ? /* Some */[/* AlignItems */Block.__(34, [alignItems[0]])] : /* None */0,
                                                                          /* :: */[
                                                                            alignSelf ? /* Some */[/* AlignSelf */Block.__(35, [alignSelf[0]])] : /* None */0,
                                                                            /* :: */[
                                                                              alignContent ? /* Some */[/* AlignContent */Block.__(36, [alignContent[0]])] : /* None */0,
                                                                              /* :: */[
                                                                                overflow ? /* Some */[/* Overflow */Block.__(37, [overflow[0]])] : /* None */0,
                                                                                /* :: */[
                                                                                  flex ? /* Some */[/* Flex */Block.__(38, [flex[0]])] : /* None */0,
                                                                                  /* :: */[
                                                                                    flexGrow ? /* Some */[/* FlexGrow */Block.__(39, [flexGrow[0]])] : /* None */0,
                                                                                    /* :: */[
                                                                                      flexShrink ? /* Some */[/* FlexShrink */Block.__(40, [flexShrink[0]])] : /* None */0,
                                                                                      /* :: */[
                                                                                        flexBasisi ? /* Some */[/* FlexBasisi */Block.__(41, [flexBasisi[0]])] : /* None */0,
                                                                                        /* :: */[
                                                                                          flexBasis ? /* Some */[/* FlexBasis */Block.__(42, [flexBasis[0]])] : /* None */0,
                                                                                          /* :: */[
                                                                                            shadowColor ? /* Some */[/* ShadowColor */Block.__(43, [shadowColor[0]])] : /* None */0,
                                                                                            /* :: */[
                                                                                              tmp,
                                                                                              /* :: */[
                                                                                                shadowOpacity ? /* Some */[/* ShadowOpacity */Block.__(45, [shadowOpacity[0]])] : /* None */0,
                                                                                                /* :: */[
                                                                                                  shadowRadius ? /* Some */[/* ShadowRadius */Block.__(46, [shadowRadius[0]])] : /* None */0,
                                                                                                  /* :: */[
                                                                                                    transform ? /* Some */[/* Transform */Block.__(47, [transform[0]])] : /* None */0,
                                                                                                    /* :: */[
                                                                                                      backfaceVisibilty ? /* Some */[/* BackfaceVisibilty */Block.__(48, [backfaceVisibilty[0]])] : /* None */0,
                                                                                                      /* :: */[
                                                                                                        backgroundColor ? /* Some */[/* BackgroundColor */Block.__(49, [backgroundColor[0]])] : /* None */0,
                                                                                                        /* :: */[
                                                                                                          borderColor ? /* Some */[/* BorderColor */Block.__(50, [borderColor[0]])] : /* None */0,
                                                                                                          /* :: */[
                                                                                                            borderTopColor ? /* Some */[/* BorderTopColor */Block.__(51, [borderTopColor[0]])] : /* None */0,
                                                                                                            /* :: */[
                                                                                                              borderBottomColor ? /* Some */[/* BorderBottomColor */Block.__(52, [borderBottomColor[0]])] : /* None */0,
                                                                                                              /* :: */[
                                                                                                                borderLeftColor ? /* Some */[/* BorderLeftColor */Block.__(53, [borderLeftColor[0]])] : /* None */0,
                                                                                                                /* :: */[
                                                                                                                  borderRightColor ? /* Some */[/* BorderRightColor */Block.__(54, [borderRightColor[0]])] : /* None */0,
                                                                                                                  /* :: */[
                                                                                                                    borderRadius ? /* Some */[/* BorderRadius */Block.__(55, [borderRadius[0]])] : /* None */0,
                                                                                                                    /* :: */[
                                                                                                                      borderTopRightRadius ? /* Some */[/* BorderTopRightRadius */Block.__(56, [borderTopRightRadius[0]])] : /* None */0,
                                                                                                                      /* :: */[
                                                                                                                        borderBottomLeftRadius ? /* Some */[/* BorderBottomLeftRadius */Block.__(57, [borderBottomLeftRadius[0]])] : /* None */0,
                                                                                                                        /* :: */[
                                                                                                                          borderBottomRightRadius ? /* Some */[/* BorderBottomRightRadius */Block.__(58, [borderBottomRightRadius[0]])] : /* None */0,
                                                                                                                          /* :: */[
                                                                                                                            borderTopLeftRadius ? /* Some */[/* BorderTopLeftRadius */Block.__(59, [borderTopLeftRadius[0]])] : /* None */0,
                                                                                                                            /* :: */[
                                                                                                                              borderStyle ? /* Some */[/* BorderStyle */Block.__(60, [borderStyle[0]])] : /* None */0,
                                                                                                                              /* :: */[
                                                                                                                                opacity ? /* Some */[/* Opacity */Block.__(61, [opacity[0]])] : /* None */0,
                                                                                                                                /* :: */[
                                                                                                                                  elevation ? /* Some */[/* Elevation */Block.__(62, [elevation[0]])] : /* None */0,
                                                                                                                                  /* :: */[
                                                                                                                                    color ? /* Some */[/* Color */Block.__(63, [color[0]])] : /* None */0,
                                                                                                                                    /* :: */[
                                                                                                                                      fontFamily ? /* Some */[/* FontFamily */Block.__(64, [fontFamily[0]])] : /* None */0,
                                                                                                                                      /* :: */[
                                                                                                                                        fontSize ? /* Some */[/* FontSize */Block.__(65, [fontSize[0]])] : /* None */0,
                                                                                                                                        /* :: */[
                                                                                                                                          fontStyle ? /* Some */[/* FontStyle */Block.__(66, [fontStyle[0]])] : /* None */0,
                                                                                                                                          /* :: */[
                                                                                                                                            fontWeight ? /* Some */[/* FontWeight */Block.__(67, [fontWeight[0]])] : /* None */0,
                                                                                                                                            /* :: */[
                                                                                                                                              fontVariant ? /* Some */[/* FontVariant */Block.__(68, [fontVariant[0]])] : /* None */0,
                                                                                                                                              /* :: */[
                                                                                                                                                tmp$1,
                                                                                                                                                /* :: */[
                                                                                                                                                  textShadowRadius ? /* Some */[/* TextShadowRadius */Block.__(70, [textShadowRadius[0]])] : /* None */0,
                                                                                                                                                  /* :: */[
                                                                                                                                                    textShadowColor ? /* Some */[/* TextShadowColor */Block.__(71, [textShadowColor[0]])] : /* None */0,
                                                                                                                                                    /* :: */[
                                                                                                                                                      letterSpacing ? /* Some */[/* LetterSpacing */Block.__(72, [letterSpacing[0]])] : /* None */0,
                                                                                                                                                      /* :: */[
                                                                                                                                                        lineHeight ? /* Some */[/* LineHeight */Block.__(73, [lineHeight[0]])] : /* None */0,
                                                                                                                                                        /* :: */[
                                                                                                                                                          textAlign ? /* Some */[/* TextAlign */Block.__(74, [textAlign[0]])] : /* None */0,
                                                                                                                                                          /* :: */[
                                                                                                                                                            textAlignVertical ? /* Some */[/* TextAlignVertical */Block.__(75, [textAlignVertical[0]])] : /* None */0,
                                                                                                                                                            /* :: */[
                                                                                                                                                              includeFontPadding ? /* Some */[/* IncludeFontPadding */Block.__(76, [includeFontPadding[0]])] : /* None */0,
                                                                                                                                                              /* :: */[
                                                                                                                                                                textDecorationLine ? /* Some */[/* TextDecorationLine */Block.__(77, [textDecorationLine[0]])] : /* None */0,
                                                                                                                                                                /* :: */[
                                                                                                                                                                  textDecorationColor ? /* Some */[/* TextDecorationColor */Block.__(78, [textDecorationColor[0]])] : /* None */0,
                                                                                                                                                                  /* :: */[
                                                                                                                                                                    writingDirection ? /* Some */[/* WritingDirection */Block.__(79, [writingDirection[0]])] : /* None */0,
                                                                                                                                                                    /* :: */[
                                                                                                                                                                      resizeMode ? /* Some */[/* ResizeMode */Block.__(80, [resizeMode[0]])] : /* None */0,
                                                                                                                                                                      /* :: */[
                                                                                                                                                                        tintColor ? /* Some */[/* TintColor */Block.__(81, [tintColor[0]])] : /* None */0,
                                                                                                                                                                        /* :: */[
                                                                                                                                                                          overlayColor ? /* Some */[/* OverlayColor */Block.__(82, [overlayColor[0]])] : /* None */0,
                                                                                                                                                                          /* :: */[
                                                                                                                                                                            tmp$2,
                                                                                                                                                                            /* :: */[
                                                                                                                                                                              tmp$3,
                                                                                                                                                                              /* :: */[
                                                                                                                                                                                tmp$4,
                                                                                                                                                                                /* :: */[
                                                                                                                                                                                  tmp$5,
                                                                                                                                                                                  /* [] */0
                                                                                                                                                                                ]
                                                                                                                                                                              ]
                                                                                                                                                                            ]
                                                                                                                                                                          ]
                                                                                                                                                                        ]
                                                                                                                                                                      ]
                                                                                                                                                                    ]
                                                                                                                                                                  ]
                                                                                                                                                                ]
                                                                                                                                                              ]
                                                                                                                                                            ]
                                                                                                                                                          ]
                                                                                                                                                        ]
                                                                                                                                                      ]
                                                                                                                                                    ]
                                                                                                                                                  ]
                                                                                                                                                ]
                                                                                                                                              ]
                                                                                                                                            ]
                                                                                                                                          ]
                                                                                                                                        ]
                                                                                                                                      ]
                                                                                                                                    ]
                                                                                                                                  ]
                                                                                                                                ]
                                                                                                                              ]
                                                                                                                            ]
                                                                                                                          ]
                                                                                                                        ]
                                                                                                                      ]
                                                                                                                    ]
                                                                                                                  ]
                                                                                                                ]
                                                                                                              ]
                                                                                                            ]
                                                                                                          ]
                                                                                                        ]
                                                                                                      ]
                                                                                                    ]
                                                                                                  ]
                                                                                                ]
                                                                                              ]
                                                                                            ]
                                                                                          ]
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ];
      var stylesProps = /* :: */[
        stylesProps_000,
        stylesProps_001
      ];
      var styles = List.fold_left((function (styles, style) {
              if (style) {
                return /* :: */[
                        style[0],
                        styles
                      ];
              } else {
                return styles;
              }
            }), /* [] */0, stylesProps);
      return React.createElement("div", {
                  className: Nice.css(styles)
                }, children);
    });
  return newrecord;
}

var Box = /* module */[
  /* component */component,
  /* make */make
];

var partial_arg = /* Some */[/* Inline */2];

function make$1(param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18, param$19, param$20, param$21, param$22, param$23, param$24, param$25, param$26, param$27, param$28, param$29, param$30, param$31, param$32, param$33, param$34, param$35, param$36, param$37, param$38, param$39, param$40, param$41, param$42, param$43, param$44, param$45, param$46, param$47, param$48, param$49, param$50, param$51, param$52, param$53, param$54, param$55, param$56, param$57, param$58, param$59, param$60, param$61, param$62, param$63, param$64, param$65, param$66, param$67, param$68, param$69, param$70, param$71, param$72, param$73, param$74, param$75, param$76, param$77, param$78, param$79, param$80, param$81, param$82, param$83, param$84, param$85, param$86) {
  return make(partial_arg, param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18, param$19, param$20, param$21, param$22, param$23, param$24, param$25, param$26, param$27, param$28, param$29, param$30, param$31, param$32, param$33, param$34, param$35, param$36, param$37, param$38, param$39, param$40, param$41, param$42, param$43, param$44, param$45, param$46, param$47, param$48, param$49, param$50, param$51, param$52, param$53, param$54, param$55, param$56, param$57, param$58, param$59, param$60, param$61, param$62, param$63, param$64, param$65, param$66, param$67, param$68, param$69, param$70, param$71, param$72, param$73, param$74, param$75, param$76, param$77, param$78, param$79, param$80, param$81, param$82, param$83, param$84, param$85, param$86);
}

var Inline = /* module */[/* make */make$1];

var partial_arg$1 = /* Some */[/* InlineBlock */3];

function make$2(param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18, param$19, param$20, param$21, param$22, param$23, param$24, param$25, param$26, param$27, param$28, param$29, param$30, param$31, param$32, param$33, param$34, param$35, param$36, param$37, param$38, param$39, param$40, param$41, param$42, param$43, param$44, param$45, param$46, param$47, param$48, param$49, param$50, param$51, param$52, param$53, param$54, param$55, param$56, param$57, param$58, param$59, param$60, param$61, param$62, param$63, param$64, param$65, param$66, param$67, param$68, param$69, param$70, param$71, param$72, param$73, param$74, param$75, param$76, param$77, param$78, param$79, param$80, param$81, param$82, param$83, param$84, param$85, param$86) {
  return make(partial_arg$1, param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18, param$19, param$20, param$21, param$22, param$23, param$24, param$25, param$26, param$27, param$28, param$29, param$30, param$31, param$32, param$33, param$34, param$35, param$36, param$37, param$38, param$39, param$40, param$41, param$42, param$43, param$44, param$45, param$46, param$47, param$48, param$49, param$50, param$51, param$52, param$53, param$54, param$55, param$56, param$57, param$58, param$59, param$60, param$61, param$62, param$63, param$64, param$65, param$66, param$67, param$68, param$69, param$70, param$71, param$72, param$73, param$74, param$75, param$76, param$77, param$78, param$79, param$80, param$81, param$82, param$83, param$84, param$85, param$86);
}

var InlineBlock = /* module */[/* make */make$2];

function make$3(param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18, param$19, param$20, param$21, param$22, param$23, param$24, param$25, param$26, param$27, param$28, param$29) {
  var partial_arg = /* Some */[/* Row */0];
  var partial_arg$1 = /* Some */[/* Flex */4];
  return (function (param$30, param$31, param$32, param$33, param$34, param$35, param$36, param$37, param$38, param$39, param$40, param$41, param$42, param$43, param$44, param$45, param$46, param$47, param$48, param$49, param$50, param$51, param$52, param$53, param$54, param$55, param$56, param$57, param$58, param$59, param$60, param$61, param$62, param$63, param$64, param$65, param$66, param$67, param$68, param$69, param$70, param$71, param$72, param$73, param$74, param$75, param$76, param$77, param$78, param$79, param$80, param$81, param$82, param$83, param$84, param$85) {
      return make(partial_arg$1, param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18, param$19, param$20, param$21, param$22, param$23, param$24, param$25, param$26, param$27, param$28, param$29, partial_arg, param$30, param$31, param$32, param$33, param$34, param$35, param$36, param$37, param$38, param$39, param$40, param$41, param$42, param$43, param$44, param$45, param$46, param$47, param$48, param$49, param$50, param$51, param$52, param$53, param$54, param$55, param$56, param$57, param$58, param$59, param$60, param$61, param$62, param$63, param$64, param$65, param$66, param$67, param$68, param$69, param$70, param$71, param$72, param$73, param$74, param$75, param$76, param$77, param$78, param$79, param$80, param$81, param$82, param$83, param$84, param$85);
    });
}

var Row = /* module */[/* make */make$3];

function make$4(param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18, param$19, param$20, param$21, param$22, param$23, param$24, param$25, param$26, param$27, param$28, param$29) {
  var partial_arg = /* Some */[/* Column */2];
  var partial_arg$1 = /* Some */[/* Flex */4];
  return (function (param$30, param$31, param$32, param$33, param$34, param$35, param$36, param$37, param$38, param$39, param$40, param$41, param$42, param$43, param$44, param$45, param$46, param$47, param$48, param$49, param$50, param$51, param$52, param$53, param$54, param$55, param$56, param$57, param$58, param$59, param$60, param$61, param$62, param$63, param$64, param$65, param$66, param$67, param$68, param$69, param$70, param$71, param$72, param$73, param$74, param$75, param$76, param$77, param$78, param$79, param$80, param$81, param$82, param$83, param$84, param$85) {
      return make(partial_arg$1, param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8, param$9, param$10, param$11, param$12, param$13, param$14, param$15, param$16, param$17, param$18, param$19, param$20, param$21, param$22, param$23, param$24, param$25, param$26, param$27, param$28, param$29, partial_arg, param$30, param$31, param$32, param$33, param$34, param$35, param$36, param$37, param$38, param$39, param$40, param$41, param$42, param$43, param$44, param$45, param$46, param$47, param$48, param$49, param$50, param$51, param$52, param$53, param$54, param$55, param$56, param$57, param$58, param$59, param$60, param$61, param$62, param$63, param$64, param$65, param$66, param$67, param$68, param$69, param$70, param$71, param$72, param$73, param$74, param$75, param$76, param$77, param$78, param$79, param$80, param$81, param$82, param$83, param$84, param$85);
    });
}

var Col = /* module */[/* make */make$4];

exports.Box         = Box;
exports.Inline      = Inline;
exports.InlineBlock = InlineBlock;
exports.Row         = Row;
exports.Col         = Col;
/* component Not a pure module */
